export {ReactComponent as AbvWeak} from "./svgs/abvWeak.svg"
export {ReactComponent as AbvMedium} from "./svgs/abvMedium.svg"
export {ReactComponent as AbvStrong} from "./svgs/abvFull.svg"
export {ReactComponent as IbuWeak} from "./svgs/ibuWeak.svg"
export {ReactComponent as IbuMedium} from "./svgs/ibuMedium.svg"
export {ReactComponent as IbuStrong} from "./svgs/ibuStrong.svg"